spring.jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    properties:
        hibernate.format_sql: true

    show-sql: true
hibernate.connection.url:
hibernate:
    dialect:aa
spring:
    jpa:
        database-platform=org:
            hibernate:
                connection:
                    url: MySQL5InnoDBDialect # ? 3? ???? ??? ?? ? ? ??? ?? 04.28
spring.datasource:
#    hikari.maxium-pool-size: 4
    url: jdbc:mysql://phtfaw4p6a970uc0.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/y9vehek9t8k930yo
# jdbc:mysql://localhost:3306/board
    username: sgaa76dftp4zc3qd
    password: wym9t50901ws39os
    driver-class-name: com.mysql.cj.jdbc.Driver

