spring.jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    properties:
        hibernate.format_sql: true

    show-sql: true
spring:
    jpa:
        database-platform=org:
            hibernate:
                connection:
                    url: MySQL5InnoDBDialect # ? 3? ???? ??? ?? ? ? ??? ?? 04.28
spring.datasource:
#    hikari.maxium-pool-size: 4
    url: jdbc:mysql://localhost:3306/fast_sns
    username: root
    password:
# jdbc:mysql://localhost:3306/board
#    username: sgaa76dftp4zc3qd
#    password: wym9t50901ws39os
    driver-class-name: com.mysql.cj.jdbc.Driver


jwt:
    secret-key: fast_campus.sns-application-2022.secret_key
    # 30 days
    token.expired-time-ms: 2592000000